site_name: Openscad Python fork
site_url: https://www.guenther-sohler.net/openscad/docs
repo_url: https://github.com/gsohler/openscad/
theme:
  name: material
  highlightjs: true
  features:
    - navigation.footer
    - content.tabs.link
    - content.code.copy
nav:
  - Getting Started: index.md
  - Combining Objects: combining_objects.md
  - Positioning Objects: positioning_objects.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
