site_name: Openscad Python fork
site_url: https://www.guenther-sohler.net/openscad/docs
repo_url: https://github.com/gsohler/openscad/
theme:
  name: material
  highlightjs: true
  features:
    - content.tabs.link
    - navigation.footer
nav:
  - Getting Started: index.md
  - Combining Objects: combining_objects.md
  - Positioning Objects: positioning_objects.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
